name: 'Deploy to S3'
description: ' Deploying to AWS S3'
inputs:
  bucket:
    description: 'The S3 bucket name'
    required: true
  bucket-region:
    description: 'The region of S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The deployable files to S3'
    required: true
outputs:
  website-url:
    description: 'The url of the deployed site'
runs:
  using: 'docker'
  image: 'Dockerfile'
