name: 'Deploy to AWS S3'
description: 'Deploy static website to S3'
inputs:
  bucket:
    description: 'The S3 bucket name'
    required: true
  bucket-region:
    description: 'The region of S3 bucket'
    required: false
    default: 'us-est-1'
  dist-folder:
    description: 'The deployable files to S3'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
